services:
  mongodb:
    image: mongo:7
    container_name: processadorf360-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: processadorf360-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  api:
    build:
      context: .
      dockerfile: src/ProcessadorTarefasF360.Api/Dockerfile
    container_name: processadorf360-api
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8081:8080"

  worker:
    build:
      context: .
      dockerfile: src/ProcessadorTarefasF360.Worker/Dockerfile
    container_name: processadorf360-worker
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      DOTNET_ENVIRONMENT: Development

volumes:
  mongo_data:
